# Generated by Django 4.1.7 on 2023-02-19 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Category title')),
                ('description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Category description')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Product title')),
                ('description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Product description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='product price')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='products', to='webapp.category', verbose_name='Category')),
            ],
        ),
    ]
